/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package csnd6;

import android.webkit.JavascriptInterface;

public class CsoundOboe {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CsoundOboe(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CsoundOboe obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        csndJNI.delete_CsoundOboe(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CsoundOboe() {
    this(csndJNI.new_CsoundOboe(), true);
  }

  public void internal_reset() {
    csndJNI.CsoundOboe_internal_reset(swigCPtr, this);
  }

  public SWIGTYPE_p_oboe__DataCallbackResult onAudioReady(SWIGTYPE_p_oboe__AudioStream oboeStream, SWIGTYPE_p_void audio_data, SWIGTYPE_p_int32_t frame_count) {
    return new SWIGTYPE_p_oboe__DataCallbackResult(csndJNI.CsoundOboe_onAudioReady(swigCPtr, this, SWIGTYPE_p_oboe__AudioStream.getCPtr(oboeStream), SWIGTYPE_p_void.getCPtr(audio_data), SWIGTYPE_p_int32_t.getCPtr(frame_count)), true);
  }

  @JavascriptInterface
public
 int Start() {
    return csndJNI.CsoundOboe_Start(swigCPtr, this);
  }

  @JavascriptInterface
public
 int Perform() {
    return csndJNI.CsoundOboe_Perform(swigCPtr, this);
  }

  @JavascriptInterface
public
 void Stop() {
    csndJNI.CsoundOboe_Stop(swigCPtr, this);
  }

  @JavascriptInterface
public
 int cleanup() {
    return csndJNI.CsoundOboe_cleanup(swigCPtr, this);
  }

  @JavascriptInterface
public
 int compileCsd(String csd) {
    return csndJNI.CsoundOboe_compileCsd(swigCPtr, this, csd);
  }

  @JavascriptInterface
public
 int compileCsdText(String csd_text) {
    return csndJNI.CsoundOboe_compileCsdText(swigCPtr, this, csd_text);
  }

  @JavascriptInterface
public
 int compileOrc(String str) {
    return csndJNI.CsoundOboe_compileOrc(swigCPtr, this, str);
  }

  @JavascriptInterface
public
 double evalCode(String str) {
    return csndJNI.CsoundOboe_evalCode(swigCPtr, this, str);
  }

  @JavascriptInterface
public
 double get0dBFS() {
    return csndJNI.CsoundOboe_get0dBFS(swigCPtr, this);
  }

  @JavascriptInterface
public
 int getAPIVersion() {
    return csndJNI.CsoundOboe_getAPIVersion(swigCPtr, this);
  }

  @JavascriptInterface
public
 void getAudioChannel(String name, SWIGTYPE_p_double samples) {
    csndJNI.CsoundOboe_getAudioChannel(swigCPtr, this, name, SWIGTYPE_p_double.getCPtr(samples));
  }

  @JavascriptInterface
public
 SWIGTYPE_p_CSOUND_ getCsound() {
    long cPtr = csndJNI.CsoundOboe_getCsound(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CSOUND_(cPtr, false);
  }

  @JavascriptInterface
public
 double getChannel(String name) {
    return csndJNI.CsoundOboe_getChannel(swigCPtr, this, name);
  }

  @JavascriptInterface
public
 double getControlChannel(String name) {
    return csndJNI.CsoundOboe_getControlChannel(swigCPtr, this, name);
  }

  @JavascriptInterface
public
 int getCurrentTimeSamples() {
    return csndJNI.CsoundOboe_getCurrentTimeSamples(swigCPtr, this);
  }

  @JavascriptInterface
public
 String getEnv(String name) {
    return csndJNI.CsoundOboe_getEnv(swigCPtr, this, name);
  }

  @JavascriptInterface
public
 double getKr() {
    return csndJNI.CsoundOboe_getKr(swigCPtr, this);
  }

  @JavascriptInterface
public
 int getKsmps() {
    return csndJNI.CsoundOboe_getKsmps(swigCPtr, this);
  }

  @JavascriptInterface
public
 int getMessageLevel() {
    return csndJNI.CsoundOboe_getMessageLevel(swigCPtr, this);
  }

  @JavascriptInterface
public
 int getNchnls() {
    return csndJNI.CsoundOboe_getNchnls(swigCPtr, this);
  }

  @JavascriptInterface
public
 int getNchnlsInput() {
    return csndJNI.CsoundOboe_getNchnlsInput(swigCPtr, this);
  }

  @JavascriptInterface
public
 String getOutputName() {
    return csndJNI.CsoundOboe_getOutputName(swigCPtr, this);
  }

  @JavascriptInterface
public
 double getScoreOffsetSeconds() {
    return csndJNI.CsoundOboe_getScoreOffsetSeconds(swigCPtr, this);
  }

  @JavascriptInterface
public
 double getScoreTime() {
    return csndJNI.CsoundOboe_getScoreTime(swigCPtr, this);
  }

  @JavascriptInterface
public
 double getSr() {
    return csndJNI.CsoundOboe_getSr(swigCPtr, this);
  }

  @JavascriptInterface
public
 void getStringChannel(String name, String string) {
    csndJNI.CsoundOboe_getStringChannel(swigCPtr, this, name, string);
  }

  @JavascriptInterface
public
 int getVersion() {
    return csndJNI.CsoundOboe_getVersion(swigCPtr, this);
  }

  @JavascriptInterface
public
 void inputMessage(String message) {
    csndJNI.CsoundOboe_inputMessage(swigCPtr, this, message);
  }

  @JavascriptInterface
public
 int isScorePending() {
    return csndJNI.CsoundOboe_isScorePending(swigCPtr, this);
  }

  @JavascriptInterface
public
 void keyPressed(char c) {
    csndJNI.CsoundOboe_keyPressed(swigCPtr, this, c);
  }

  @JavascriptInterface
public
 void message(String text) {
    csndJNI.CsoundOboe_message(swigCPtr, this, text);
  }

  @JavascriptInterface
public
 int perform() {
    return csndJNI.CsoundOboe_perform(swigCPtr, this);
  }

  public int pvsinSet(PVSDATEXT value, String name) {
    return csndJNI.CsoundOboe_pvsinSet(swigCPtr, this, PVSDATEXT.getCPtr(value), value, name);
  }

  public int pvsoutGet(PVSDATEXT value, String name) {
    return csndJNI.CsoundOboe_pvsoutGet(swigCPtr, this, PVSDATEXT.getCPtr(value), value, name);
  }

  @JavascriptInterface
public
 int readScore(String str) {
    return csndJNI.CsoundOboe_readScore(swigCPtr, this, str);
  }

  @JavascriptInterface
public
 void reset() {
    csndJNI.CsoundOboe_reset(swigCPtr, this);
  }

  @JavascriptInterface
public
 void rewindScore() {
    csndJNI.CsoundOboe_rewindScore(swigCPtr, this);
  }

  @JavascriptInterface
public
 void setInput(String name) {
    csndJNI.CsoundOboe_setInput(swigCPtr, this, name);
  }

  @JavascriptInterface
public
 int setGlobalEnv(String name, String value) {
    return csndJNI.CsoundOboe_setGlobalEnv(swigCPtr, this, name, value);
  }

  public void setMessageLevel(int messageLevel) {
    csndJNI.CsoundOboe_setMessageLevel(swigCPtr, this, messageLevel);
  }

  public void setMIDIFileInput(String name) {
    csndJNI.CsoundOboe_setMIDIFileInput(swigCPtr, this, name);
  }

  public void setMIDIFileOutput(String name) {
    csndJNI.CsoundOboe_setMIDIFileOutput(swigCPtr, this, name);
  }

  public void setMIDIInput(String name) {
    csndJNI.CsoundOboe_setMIDIInput(swigCPtr, this, name);
  }

  public void setMIDIOutput(String name) {
    csndJNI.CsoundOboe_setMIDIOutput(swigCPtr, this, name);
  }

  @JavascriptInterface
public
 int setOption(String option) {
    return csndJNI.CsoundOboe_setOption(swigCPtr, this, option);
  }

  @JavascriptInterface
public
 void setOutput(String name, String type, String format) {
    csndJNI.CsoundOboe_setOutput(swigCPtr, this, name, type, format);
  }

  @JavascriptInterface
public
 void setScoreOffsetSeconds(double time) {
    csndJNI.CsoundOboe_setScoreOffsetSeconds(swigCPtr, this, time);
  }

  @JavascriptInterface
public
 void setScorePending(int pending) {
    csndJNI.CsoundOboe_setScorePending(swigCPtr, this, pending);
  }

  @JavascriptInterface
public
 int start() {
    return csndJNI.CsoundOboe_start(swigCPtr, this);
  }

  @JavascriptInterface
public
 void stop() {
    csndJNI.CsoundOboe_stop(swigCPtr, this);
  }

  public int scoreEvent(char type, SWIGTYPE_p_double pFields, int numFields) {
    return csndJNI.CsoundOboe_scoreEvent(swigCPtr, this, type, SWIGTYPE_p_double.getCPtr(pFields), numFields);
  }

  public int runUtility(String name, int argc, SWIGTYPE_p_p_char argv) {
    return csndJNI.CsoundOboe_runUtility(swigCPtr, this, name, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public void setAudioChannel(String name, SWIGTYPE_p_double samples) {
    csndJNI.CsoundOboe_setAudioChannel(swigCPtr, this, name, SWIGTYPE_p_double.getCPtr(samples));
  }

  @JavascriptInterface
public
 void setChannel(String name, double value) {
    csndJNI.CsoundOboe_setChannel__SWIG_0(swigCPtr, this, name, value);
  }

  @JavascriptInterface
public
 void setControlChannel(String name, double value) {
    csndJNI.CsoundOboe_setControlChannel(swigCPtr, this, name, value);
  }

  public void setChannel(String name, String string) {
    csndJNI.CsoundOboe_setChannel__SWIG_1(swigCPtr, this, name, string);
  }

  @JavascriptInterface
public
 void setStringChannel(String name, String string) {
    csndJNI.CsoundOboe_setStringChannel(swigCPtr, this, name, string);
  }

  @JavascriptInterface
public
 int tableLength(int table) {
    return csndJNI.CsoundOboe_tableLength(swigCPtr, this, table);
  }

  @JavascriptInterface
public
 double tableGet(int table, int index) {
    return csndJNI.CsoundOboe_tableGet(swigCPtr, this, table, index);
  }

  @JavascriptInterface
public
 void tableSet(int table, int index, double value) {
    csndJNI.CsoundOboe_tableSet(swigCPtr, this, table, index, value);
  }

}
